apiVersion: v1
kind: Pod
metadata:
  name: gru-training
spec:
  restartPolicy: Never
  nodeName: dell01
  containers:
  - image: wannazjx/pytorch-luo:1.1
    name: torch
    command: [ "sh", "-c", "cd /workspace/code/pytorch/word_language_model && python -u main.py --cuda --epochs 25 --model GRU --data /workspace/dataset/common/wikitext-2/data1"]
    volumeMounts:
    - mountPath: /workspace
      name: code
    - mountPath: /dev/shm
      name: cache-volume
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
  volumes:
  - name: code
    hostPath:
      path: /root/wanna/workspace
      type: Directory
  - name: cache-volume
    emptyDir:
      medium: Memory
