apiVersion: v1
kind: Pod
metadata:
  name: resnet-training
spec:
  restartPolicy: Never
  nodeName: dell01
  containers:
  - image: wannazjx/pytorch-luo:1.1
    name: torch
    command: [ "sh", "-c", "nvidia-smi && cd /workspace/code/pytorch/imagenet && python -u main.py -a resnet18 --epochs 15 -b 16 -p 400 /workspace/dataset/common/mini-images/data"]
    volumeMounts:
    - mountPath: /workspace
      name: code
    - mountPath: /dev/shm
      name: cache-volume
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
  volumes:
  - name: code
    hostPath:
      path: /root/wanna/workspace
      type: Directory
  - name: cache-volume
    emptyDir:
      medium: Memory
